applications:
  # Conveyancer
  conveyancer-ui:
    repo: git@github.com:LandRegistry/digital-street-conveyancer-ui.git
    branch: master
  case-management-api:
    repo: git@github.com:LandRegistry/digital-street-case-management-api.git
    branch: master
  # HMLR
  title-ui:
    repo: git@github.com:LandRegistry/digital-street-title-ui.git
    branch: master
  title-api:
    repo: git@github.com:LandRegistry/digital-street-title-api.git
    branch: master
  # Lender
  lender-ui:
    repo: git@github.com:LandRegistry/digital-street-lender-ui.git
    branch: master
  lender-management-api:
    repo: git@github.com:LandRegistry/digital-street-lender-management-api.git
    branch: master
  # Payment
  payment-ui:
    repo: git@github.com:LandRegistry/digital-street-payment-ui.git
    branch: master
